# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
         Symfony\Component\Security\Core\User\User:
              algorithm: bcrypt

    firewalls:
        prueba_firewall:
            pattern: ^/
            http_basic:
               realm: "Test de Acceso"

    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN}

    providers:
        in_memory:
           memory:
               users:
                    #Encoder: bcrypt, valor: user
                    usuario: { password:  $2y$13$NkuH/vqReTofhLB/bmA4lO6YbfWp6vjKEtiiJRlzb73PcIqWIfiHe, roles: 'ROLE_USER' }

                    #Encoder: bcrypt, valor: 123
                    admin: { password: $2y$13$DM.o1l88PSxgrC1JzgrgeulQ87TpnjmcynbrBL/fztEULxYcsb20m, roles: 'ROLE_ADMIN'}
